Run `build` script during pre-commit to validate build function

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -52,6 +52,20 @@ function validate_ts() {
 }
 validate_ts &
 
+function build() {
+    echo "${YELLOW}[pre-commit]${BLUE} Running \`yarn build\`... ${WHITE}"
+
+    OUTPUT=$(yarn build 2>&1)
+     if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}Build failed."
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} Build Completed!${WHITE}"
+}
+build &
+
 # Go through each background task
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
